const GETTERS = {
    BANNERS: {
        GET_SAVE_BANNER: 'GET_SAVE_BANNER'
    },
    COPY: {
        CATEGORIES: 'CATEGORIES',
        RATINGS: 'RATINGS',
        UNRATINGS: 'UNRATINGS',

        RATING_VALUES: 'RATING_VALUES',
        UNRATING_VALUES: 'UNRATING_VALUES',
        UNRATING_DESCRIPTION: 'UNRATING_DESCRIPTION'
    },
    MODES: {
        UPLOAD_STATUS: 'UPLOAD_STATUS',
        VIEW_MODE: 'VIEW_MODE',
        SUMMARY_MODE: 'SUMMARY_MODE',
        SECTION_HIDDEN: 'SECTION_HIDDEN',
    },
    SURVEY: {
        GET_META: 'GET_META',
        GET_SECTIONS: 'GET_SECTIONS',
        GET_SECTION: 'GET_SECTION',
        IS_LOADED: 'IS_LOADED',
        GET_PROGRESS: 'GET_PROGRESS',
        GET_SCORE: 'GET_SCORE',
        GET_COMPLETED: 'GET_COMPLETED',
        GET_TOTAL: 'GET_TOTAL',
    },
    SURVEYS: {
        GET_SURVEYS: 'GET_SURVEYS',
        GET_SURVEY: 'GET_SURVEY'
    }
};

export { GETTERS };
