const MUTATIONS = {
    BANNERS: {
        SAVE_BANNER: 'SAVE_BANNER'
    },
    BLANKS: {
        SET_CUSTOM_SOURCE: 'SET_CUSTOM_SOURCE',
        SET_BLANKS: 'SET_BLANKS',
        SET_ERROR: 'SET_ERROR'
    },
    MODES: {
        ENABLE_UPLOADER: 'ENABLE_UPLOADER',
        DISABLE_UPLOADER: 'DISABLE_UPLOADER',

        TOGGLE_VIEW_MODE: 'TOGGLE_VIEW_MODE',
        ENABLE_VIEW_MODE: 'ENABLE_VIEW_MODE',

        TOGGLE_SUMMARY_MODE: 'TOGGLE_SUMMARY_MODE',
        ENABLE_SUMMARY_MODE: 'ENABLE_SUMMARY_MODE',

        TOGGLE_SECTION: 'TOGGLE_SECTION',
        HIDE_SECTION: 'HIDE_SECTION',
        SHOW_SECTION: 'SHOW_SECTION',
    },
    SURVEY: {
        SET_ID: 'SET_ID',
        SET_NAME: 'SET_NAME',

        SET_TYPE: 'SET_TYPE',
        SET_VERSION: 'SET_VERSION',
        SET_UPDATED: 'SET_UPDATED',
        SET_SECTIONS: 'SET_SECTIONS',

        SET_RATING: 'SET_RATING',
        SET_COMMENT: 'SET_COMMENT',
        CALCULATE_SECTION: 'CALCULATE_SECTION',
        CALCULATE_SURVEY: 'CALCULATE_SURVEY',

        LOAD_SURVEY: 'LOAD_SURVEY',
        UNLOAD_SURVEY: 'UNLOAD_SURVEY',
    },
    SURVEYS: {
        SET_SURVEYS: 'SET_SURVEYS',
    }
};

export { MUTATIONS };
